### ISSUE TITLE
Add metadata enumeration element for NOAA Product Uncertainty 2.0

### ISSUE THREAD

**Issue by brian-r-calder** [OpenNavigationSurface/BAG#112]
At the WG meeting at CHC'24, documented [here](https://github.com/OpenNavigationSurface/WorkingGroup/blob/main/Meetings/2024-05_CHC24/Notes.md), the WG voted unanimously to accept a NOAA proposal for a new metadata uncertainty tag for BAG to describe their required product metadata uncertainty convention; conversation documented [here](https://github.com/OpenNavigationSurface/WorkingGroup/issues/2).

The requirements are:

1. Determine a default, unique, unambiguous name for the metadata tag to be added.
2. Add a metadata tag to the schema [here](https://github.com/OpenNavigationSurface/BAG/blob/master/configdata/ISO19139/bag/bagCodelists.xml).
3. Bump BAG version (in conjunction with any other modifications merged at the same time).
4. Update FSD documentation to document the NOAA uncertainty specification metadata tag, and provide a link to a permanent version of the description document.

Note that the other items in the [discussion](https://github.com/OpenNavigationSurface/WorkingGroup/issues/2) (issues 1/2) are deferred until later and are not part of this enhancement request (see [here](https://github.com/OpenNavigationSurface/WorkingGroup/issues/9)).

**Comment by selimnairb** [comment]
@mattwilson27 I wanted to start the discussion of what the name for the metadata tag should be. 

I think versioning this is a good idea.

NOAA standard product uncertainty V1.0 is denoted by the identifier "productUncert", which we can mark as deprecated in its `gml:description` element.

As for what the identifier for NOAA standard product uncertainty V2.0 should be, I would recommend something like "noaaProduct_2024.08". I like dates (usually [YYYY.MM](http://yyyy.mm/) is enough, though maybe YYYY is sufficient for this) as version indicators in metadata elements.

We already do this for the NOAA georeferenced metadata profile, which appears as "NOAA-OCS-2022.10" in the BAG HDF encoding (for more see: https://bag.readthedocs.io/en/master/fsd/FSD-Appendices.html).

Let me know what you think. Thanks!

**Comment by mattwilson27** [comment]
@selimnairb thank you for starting the discussion and recommending the versioning to accompany the suggested naming. I think "noaaProduct_2024.08" should work fine (agreed that it is a bit cleaner without the month). 
Thanks for the insight and context.

**Comment by selimnairb** [comment]
> @selimnairb thank you for starting the discussion and recommending the versioning to accompany the suggested naming. I think "noaaProduct_2024.08" should work fine (agreed that it is a bit cleaner without the month). Thanks for the insight and context.

Just to clarify, you are proposing to use "noaaProduct_2024" (i.e., without the month)?

If this is the case, then the `<codeEntry>` element in the `<CodeListDictionary gml:id="BAG_VertUncertCode">` would look something like:
```
<codeEntry>
    <CodeDefinition gml:id="BAG_VertUncertCode_noaaProduct_2024">
        <gml:description>NOAA standard product uncertainty version 2024 (https://github.com/OpenNavigationSurface/WorkingGroup/files/15204109/MBES.Uncertainty.For.for.NOAA.s.Office.of.Coast.Survey_v1.pdf)</gml:description>
        <gml:identifier codeSpace="ISOTC211/19115">noaaProduct_2024</gml:identifier>        </CodeDefinition>
</codeEntry>
```

I think the`<gml:description>` should link to the detailed definition of the uncertainty estimation algorithm. The white paper PDF linked to above may be sufficient for that (that's up to you to decide really), but I'm not sure hosting it where it is in the ONS WorkingGroup repo files is the right place; I'd prefer a URL referencing a NOAA-controlled resource that can serve as the definitive definition. Is there such a web site?

**Comment by mattwilson27** [comment]
@selimnairb , yes, I support without the month. 
I will discuss about where is the best place to host it. I think we can host it on the Coast Survey website (though there is no link pointing to it, it could still be hosted there). I will fine out about that and let you know.

**Comment by selimnairb** [comment]
@mattwilson27 Please see the [PR](https://github.com/OpenNavigationSurface/BAG/pull/120) and let me know if you have any feedback.

**Comment by mattwilson27** [comment]
Hi @selimnairb , thank you, I had a look at the code changes and see the metadata enumeration element added for "noaa_product2024".

**Comment by selimnairb** [comment]
> Hi @selimnairb , thank you, I had a look at the code changes and see the metadata enumeration element added for "noaa_product2024".

@mattwilson27 Just to confirm, are the changes acceptable? Just want to make sure this is okay to merge and release.

**Comment by mattwilson27** [comment]
Hi @selimnairb , we had a side conversation I'm moving into the GH comments so it is maintained, my mistake not to have it here originally.

To my knowledge the changes are acceptable and ready to proceed to the merge and release. With the new metadata enumeration elements added, I understand the FSD documentation is then updated. Then I had asked if it will be up to the various vendors to implement. Also I had asked if the new vertical uncertainty is only being added to BAG 2+, or would it be available in BAG 1.X as well? We (NOAA) would hope that it would be available in BAG 1.X so as not to be coupled together with BAG 2+ timelines for implementation. 

Brian informed that the FSD documentation has been updated, with an auto render currently available here (https://baglib-fsd-dev.s3.us-east-2.amazonaws.com/sphinx/fsd/FSD-BAGStructure.html) and later to be available via readthedocs. 

Brian informed that it is up to the vendors to implement the noaa_Product2024 uncertainty, and also that the changes are only being made to BAG 2+. However, the changes are only present in bagCodelists.xml (https://github.com/OpenNavigationSurface/BAG/pull/120/files#diff-597eb93529ee1296535c0911d78ad5c946366fb50f778a13f015e8172704212f) so in theory the latest version of this file could be used to generate the XML metadata that goes into a version 1.X BAG. As mentioned above, we (NOAA) would be hopeful for this result (so that the new vertical uncertainty is available in vendor implementations of both BAG 1.X and 2.X).
