### ISSUE TITLE
Stage branch for BAG 2.0 work

### ISSUE THREAD

**Issue by tdy-blamey** [OpenNavigationSurface/BAG#19]
Create the new branch for the BAG 2.0 branch, and get 3rd party libraries updated.

- Review the existing (old) branch for BAG.
- Create a new branch for the new work, bring over any useful work from the old branch
- Get all work items entered into the issue tracker in the BAG github project.
- Get latest copies of 3rd party libs (HDF5, ZLIB, libxml2) and get the building.

**Comment by giumas** [comment]
It may be a good idea to use a package manager like conda to retrieve the 3rd party libs:

* https://anaconda.org/conda-forge/libxml2
* https://anaconda.org/conda-forge/hdf5

Such a solution would simplify the integration with other Python modules like GDAL (since BAG and GDAL have common dependencies). It would be also handy for continuous integration since it reduces the compilation time.

**Comment by jice73** [comment]
I've created a new branch called **v2** from master.  I have copied the existing work from the v2.0_cpp_api branch, and am in the process of combining these changes with the ~4 years of commits since that branch was made.

I have the newest version of the third party libraries building locally.  I have acquired Miniconda, but haven't had time to dig into it yet.  My initial thoughts are it may be a problem since it looks like it wants to mess with my Python settings, which I have set up for Teledyne-CARIS stuff.  Disclaimer - I am not a Python guy, and have only heard of virtual environment stuff, but never set it up.

I forked BAG to be able to look at the Travis CI stuff, and investigate CI via actions.
